server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keycloak.p12
    key-store-password: your_keystore_password
    key-store-type: PKCS12
    key-alias: pizzariagln
    trust-store: classpath:truststore.jks
    trust-store-password: changeit

keycloak:
  auth-server-url: https://172.31.88.152:8443/auth
  realm: pizzariaGLN
  resource: pizzaria_admin
  credentials:
    secret: adppnSe2hjv6wDDKhTjKGTPUIwbKhrDc
  use-resource-role-mappings: true

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://172.31.88.152:8443/realms/pizzariaGLN
          jwk-set-uri: https://172.31.88.152:8443/realms/pizzariaGLN/protocol/openid-connect/certs

  jpa:
    database: postgresql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://pizzariagln.c96u8sisi93d.us-east-2.rds.amazonaws.com:5432/pizzaria
    username: pizzaria_gln
    password: ay6a&2Wa2;LVL!e

logging:
  file:
    name: application.log
